### ISSUE TITLE
(Own) UVa OJ support Go 

### ISSUE THREAD

**Issue by maestrofx** [codingsince1985/UVa#1]
Hi @codingsince1985 
How do you test your go code to get "accepted verdict" since UVa doesn't support Go?

Do you create your own OJ Go-based? Interesting to know.

Thank you.

**Comment by codingsince1985** [comment]
Hi @maestrofx 
I only tested my solution against the test cases in question. There might be WAs or TLs. And I read and write files, rather than using stdio.
Cheers

**Comment by codingsince1985** [comment]
closed.
